name: CI-CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  # 1) Build + tests + couverture + analyse Sonar (via Maven)
  build-test-sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      # Génère le rapport JaCoCo (target/site/jacoco/jacoco.xml)
      - name: Build & test (JaCoCo)
        run: mvn -B -Psonar verify

      # Analyse SonarCloud (lit les props du pom.xml)
      - name: SonarCloud (Maven)
        run: mvn -B -Psonar sonar:sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }}

  # 2) Build & push image Docker vers GHCR
  docker-push:
    needs: build-test-sonar
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compute image meta (tag + owner lower)
        id: meta
        shell: bash
        run: |
          echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
          echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.meta.outputs.OWNER_LC }}/workhub-backend:${{ steps.meta.outputs.TAG }}
            ghcr.io/${{ steps.meta.outputs.OWNER_LC }}/workhub-backend:latest

  # 3) Déploiement sur la VM (vérifie la présence des secre
